### PR TITLE
Bani

### PR DESCRIPTION
**Pull request by Bani2791**
## **1. Ingress Routing**
1. **Lock** (Whitelist): Select one or more rate cards from the list of available providers. 
**Lock**: Whitelist one or more rate cards from the list of available providers.

2. **Removed:** :material-menu-right: `Auto`- Selects the least expensive path between your customer and provider, but failovers are not automated which is why this option isn't recommended.  (does not exist now)

3. **Add a note:** RTP  proxy mode: 
!!! tip "The recommended RTP Media Proxy servers are the **Closest (To ConnexCS) Server** or the **Closest (Elastic) Server**."

https://bani--connexcs-docs.netlify.app/customer/routing/

## 2. Customer
1. **Added .csv file**
Bulk Upload: Upload multiple Customers at the same time, by importing a spreadsheet file (.csv file) into ConnexCS.

2. **Add a note**
!!! note "Note that you won't be able to change the account currency once the account is created."

3. **Add routing after the customer**

Use this to add meta-data identifiers to a customer. If a customer routing is created using a template from [**Global Routing**](https://docs.connexcs.com/global-routing/), this will be the tag configured in the template.

Click the below link:
https://bani--connexcs-docs.netlify.app/customer/customer/

## 3. Main

1. **Note added in Customer>Main**
!!! note "Each specific customer's portal can be accessed by clicking on the dropdown against the customer's name."

https://docs.connexcs.com/customer/main/#access-customer-portal

## 4.  Auth

1. Highlighted:
**FQDN can be used for Ingress-only switches.**

https://bani--connexcs-docs.netlify.app/customer/auth/

## 5.  CLI

**1.Highlight**:
Management  Customer  [Customer Name]  Routing

**2. CLI**: To allow CLIs through, enter the required number or a regular expression (to match and replace).
Re-written as: To whitelist the required CLIs, enter the required number or a regular expression (to match and replace). 

**3. Re-written as**: Pre-Asserted-ID: To whitelist the required Pre-Asserted-Identities (PAID), enter the required number or a regular expression to match and replace.

**4. Added anchor text** : By default, a customer account will pass all calls, even without any configured CLI records. To change this behaviour, navigate to **Management :material-menu-right: Customer :material-menu-right: [Customer Name] :material-menu-right: Edit :material-menu-right: Verification** and enable   [**Approved CLI's Only**](https://docs.connexcs.com/customer/cli/#allow-customer-to-add-their-own-cli).

**5. Filter CLI from a large list**: You can manage large lists of numbers from our Userspace database. Once you upload the numbers under Developer :material-menu-right: Database, you can use the following options to filter by the uploaded list. Note that the filter is a partial match.

6. Developer :material-menu-right: **added in the paragraph**

**7.    **Blacklist numbers per provider****
Use**CLI Restrict** to block calls, essentially creating a Blacklist of numbers. To block a configured CLIs

**8. re-written: ## Blacklist numbers per provider**
Use **CLI Restrict** to whitelist CLIs passing through a specific provider. To whitelist a configured CLI:

1. Click **Management :material-menu-right: Rate Card**. 
2. Select **Provider Rate Card** (under the Name column).
1. Select **Properties :material-menu-right: Advanced**.
3. Enter the CLI / ANIs you want to whitelist in the **CLI Restrict** box.
4. Click **`Save`**.

**note: changed blacklist/ block to whitelist**

https://bani--connexcs-docs.netlify.app/customer/cli/

## 6. Route Stats

Route Stats displays Channel, Channel Breach, and Calls Per Second (CPS) Breach data based on individual routes.
You can see the data in the form of graphs.
1. Channels: Number of Channels allocated to the customer.
2. Channel Breach: When a customer exceeds the number of permitted channels.
3. CPS Breach: When a customer is passing more calls per second than permitted.

https://bani--connexcs-docs.netlify.app/customer/route-stats/

## 7. Latest Calls

**1. Added the section**

!!! note "Know More"
     1. To know more about Providers [click here](https://docs.connexcs.com/feature-list/#providers).
     2. To know more about Billing [click here](https://docs.connexcs.com/billing/).
     3. To know more about Logs [click here](https://docs.connexcs.com/logging/#searching-the-logs).
     4. To know more about Graphs [click here](https://docs.connexcs.com/customer-portal/cp-dashboard/#graphs).

https://bani--connexcs-docs.netlify.app/customer/latest-calls/

## 8. DID

**1. Removed**    :material-menu-right: `Auto`- Selects the least expensive path between your customer and provider. FROM RTP Media Proxy

**2. RTP Media Proxy:** This defaults to Auto but selecting a zone (by continent) is the current recommendation.
Changed to: The recommended RTP Media Proxy server is the **Closest (Elastic) Server**.  

https://bani--connexcs-docs.netlify.app/customer/did/

### CODE REVIEW

**Comment by digipigeon** [comment]
1. Whitelist / Blacklist can be considered culturally insensitive to some Americans, we should change these to allow and deny list.

One explanation has brackets, not sure why the other one does not now.

2. Currency "Note" does not display stylised (admonition)

3. admonition is incorrect, there is a title without body text, hence its all boldened.

4. Should this be an admonition?

5. Who is Homebase telecom? Is this a private information?
Why is the title changed to "Steps To Enable", this breaks the style from the other pages.
5.3. Re-written as: Pre-Asserted-ID: To whitelist the required Pre-Asserted-Identities (PAID), enter the required number or a regular expression to match and replace." - this should be match or replace.

When adding in Developer > Database, Database should contain a link taking you directly to that database page.

Blacklist - see point 1 I am not sure why are are talking about blacklist numbers per provider, when you continue to talk ab out how to whitelist?

**Comment by digipigeon** [comment]
## 1. Rewrite the Intercept Reinvite
**Auth>Advanced>Intercept Reinvite**

**Original sentence:** 
**Intercept Reinvite:** The only situation where this is recommended is when a customer's equipment doesn't support REINVITES. Enabling this may correct issues with dropped calls by having ConnexCS generate the REINVITES, which can help keep calls up if they are being disconnected by the far-end switch.

**Re-written as:** "ConnexCS responds to the INVITES." instead of "ConnexCS generate the REINVITE"

https://bani--connexcs-docs.netlify.app/customer/auth/

## 2. Delete Email log & Delay Log under documentation

**Cloudswitch>Setup>Information**

Done

## 3. Arrange the information  of basic,menu,advanced as tabs

**Cloudswitch>Setup>Integration>Webphone**

It was already done

https://bani--connexcs-docs.netlify.app/webphone/

## 4. Arrange Basic, User Access Area, Breakout,CDR, Advanced as tabs

**Cloudswitch>Setup>Integration>Portal**

It was already done

https://bani--connexcs-docs.netlify.app/setup/integrations/portal/

## 5. Cloudswitch>Setup>Config>Template

1.Explain Script forge Integration with example & descriptive

It was already done

https://docs.connexcs.com/setup/config/templates/#scriptforge-integration

2. The link under Template>Sample RSS leads Webphone to 404 Not found

Rectified

https://bani--connexcs-docs.netlify.app/setup/config/templates/

## 6.Arrange Basic, User Access Area, Breakout,CDR, Advanced as tabs 

**Cloudswitch>Setup>Integration>Portal**

It was already done

https://bani--connexcs-docs.netlify.app/setup/integrations/portal/

## 7. The link in global>contacts, does not link to Contacts
**Cloudswitch>Global>Contacts**

Rectified

https://bani--connexcs-docs.netlify.app/global/

## 8. Need to remove LRN database update as suggested by Jonathan Sir
**Cloudswitch>Routing>USA Routing**

Removed

https://bani--connexcs-docs.netlify.app/routing-usa/

## 9. Create Global Routing>Step1.1......(Instead click > it should be +)
**Cloudswitch>RoutingGlobal**

Done

https://bani--connexcs-docs.netlify.app/global-routing/

## 10. Re-write: Dialogs displays the currently active calls on the account.
**Cloudswitch>Customer>Dialogs**
**Rewritten**: Dialogs displays the "status" of currently active calls on the account.

https://bani--connexcs-docs.netlify.app/global-routing/

## 11. Add - NOTE; 1. The simulate button is used to simulate a closed circuit call. <br> 2.This closed circuit call is used to identify the Routing Issues
**Cloudswitch>Customer>Latest Calls**
**Added**
https://bani--connexcs-docs.netlify.app/customer/latest-calls/

## 12. Need to remove this as it already mentioned under Customer- IP authentication audit log
**Cloudswitch>auth>IP authentication Audit Log**

Removed
https://bani--connexcs-docs.netlify.app/customer/auth/

## 13. Remove Latency as it is not present in Control panel.
**Cloudswitch>Auth>SIP user authentication**

Removed
https://bani--connexcs-docs.netlify.app/customer/auth/#sip-user-authentication

## 14. 1. Rearrange this as Name, Email, Phone &Mobile then Contact Type.<br>2. Name: Contacts real name, change- Name: Contact's real name

**Cloudswitch>Customer>Main**

Done
https://bani--connexcs-docs.netlify.app/customer/main/

## 15. Routing global has wrong template screenshot to add tag   
**Cloudswitch>Routing Global**

Done
https://bani--connexcs-docs.netlify.app/global/

**Comment by digipigeon** [comment]
Batch  2

1. https://bani--connexcs-docs.netlify.app/customer/auth/ - no mention of reinvites
2. No Link cant check

**Comment by Bani2791** [comment]
# Batch 1: Corrections

## **1. Corrected **1.1** and **1.2****

Lock (Allow): One or more rate cards from the list of available providers.
Exclude (Deny): Exclude access to one or more rate cards in the list of available providers

https://bani--connexcs-docs.netlify.app/customer/routing/

## **2. Corrected the note admonition**

**Should this be an admonition?**- Aatif suggested this change; please let me know if any other change is required

https://bani--connexcs-docs.netlify.app/customer/customer/

## **5.1** Why is the title changed to "Steps To Enable", this breaks the style from the other pages

**removed the note**

https://bani--connexcs-docs.netlify.app/customer/cli/

### **5.3** match **and** replace replaced with match **or** replace

Re-written as: Pre-Asserted-ID: To whitelist the required Pre-Asserted-Identities (PAID), enter the required number or a regular expression to match and replace." - this should be match or replace.

https://bani--connexcs-docs.netlify.app/customer/cli/


### **When adding in Developer > Database, Database should contain a link taking you directly to that database page.**

**Added anchor text**: You can manage large lists of numbers from our Userspace database. Once you upload the numbers under Developer  [Database](https://docs.connexcs.com/developers/database/), you can use the following options to filter by the uploaded list. Note that the filter is a partial match.

### **Blacklist - see point 1 I am not sure why are are talking about blacklist numbers per provider, when you continue to talk ab out how to whitelist?**

**Changed to Allow list per provider**

https://bani--connexcs-docs.netlify.app/customer/cli/#allow-list-numbers-per-provider

## **Customer Portal > CLI**

**Changed whitelist to allow list**

## Forced
Depending on how you want to route the calls, toggle a CLI between `Forced` and `Allow list`. 

https://bani--connexcs-docs.netlify.app/customer-portal/cp-cli/

## **Homebase Telecom is a fake company** 
image

**Pull request merged**
